import React, { useState } from "react";
import { useRouter } from "next/router";
import Navbar from "../components/navbar/navbar";
import styles from "../styles/Details.module.scss";
import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Footer from "../components/footer/footer";
const inter = Inter({ subsets: ["latin"] });
const slug = ({ resdata }) => {


  const router = useRouter();
  const { slug } = router.query;
  const [startDate, setStartDate] = useState(new Date());
  const [data, setData] = useState(resdata);
  const handleChange = async (date,e) => {
  
    console.log(e);
    const res = await fetch(
      `https://history.muffinlabs.com/date/${date.getMonth()+1}/${date.getDate()}`
    )
    const resdata = await res.json();
    setData(resdata);
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Quick History - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Navbar  startDate={startDate}
        setStartDate={setStartDate}
        handleChange={handleChange}/>
      <main className={styles.main}>
      <h2 className={`${inter.className} ${styles.headDate}`} >{data.date}</h2>
        <div className={styles.infoDiv}>
          <h2 className={inter.className}>All {slug}</h2>
          {data.data[`${slug}`].map((element) => {
            return (
              <div className={inter.className}>
                <span className={styles.detailspan}>{element.year} - </span>
                <p className={styles.details}>{element.text}</p>
                <h3>Usefull Links</h3>
                {element.links.map((e) => {
                  return (
                    <ul>
                      <li>
                        <Link href={e.link}>
                          <span>{e.title}</span>
                        </Link>
                      </li>
                    </ul>
                  );
                })}
              </div>
            );
          })}
        </div>
      </main>
      <Footer/>
    </div>
  );
};
export async function getServerSideProps(context) {
  const res = await fetch(`https://history.muffinlabs.com/date`);
  const resdata = await res.json();
  return {
    props: {resdata:JSON.parse(JSON.stringify(resdata))}, // will be passed to the page component as props
  };
}

export default slug;
